export const LOGIN='LOGIN';
export const LOGIN_FAILED='LOGIN_FAILED';
export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const SIGNUP_SUCCESS='SIGNUP_SUCCESS';
export const SIGNUP_FAILED='SIGNUP_FAILED';
export const GET_ALL_USERS='GET_ALL_USERS';
export const GET_ALL_USERS_Failed="GET_ALL_USERS_Failed";
export const ADD_USER = 'ADD_USER';


export const GET_ALL_CLASSES='GET_ALL_CLASSES';
export const GET_ALL_CLASSES_FAILED="GET_ALL_CLASSES_FAILED";
export const ADD_CLASS = 'ADD_CLASS';



export const GET_ALL_CLASS_COURSES='GET_ALL_CLASS_COURSES';
export const GET_ALL_CLASS_COURSES_FAILED="GET_ALL_CLASS_COURSES_FAILED";
export const ADD_COURSE = 'ADD_COURSE';